### ISSUE TITLE
Rails 4.2 no route to "/assets/twitter/fonts/glyphicons-halflings-regular.ttf"

### ISSUE THREAD

**Issue by chabgood** [seyhunak/twitter-bootstrap-rails#884]
New rails 4.2 app I get this error a couple times, I see it in the git repository.

Started GET "/assets/twitter/fonts/glyphicons-halflings-regular.ttf" for ::1 at 2015-11-02 21:33:52 -0500

ActionController::RoutingError (No route matches [GET] "/assets/twitter/fonts/glyphicons-halflings-regular.ttf"):
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/chabgood/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/chabgood/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/chabgood/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.3ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_route.html.erb (2.1ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_table.html.erb (1.6ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.4ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (58.4ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.5ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.5ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/web-console-2.2.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/web-console-2.2.1/lib/web_console/templates/console.js.erb within layouts/javascript (39.1ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/web-console-2.2.1/lib/web_console/templates/main.js.erb within layouts/javascript (0.2ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/web-console-2.2.1/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/chabgood/.rvm/gems/ruby-2.2.3@registeryourhorse/gems/web-console-2.2.1/lib/web_console/templates/index.html.erb (89.5ms)

**Comment by yangsec888** [comment]
same problem in my project here:
I, [2016-02-17T08:37:52.402468 #12735]  INFO -- : Started GET "/assets/twitter/fonts/glyphicons-halflings-regular.ttf" for 99.88.20.39 at 2016-02-17 08:37:52 -0500
F, [2016-02-17T08:37:52.403669 #12735] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/assets/twitter/fonts/glyphicons-halflings-regular.ttf"):
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  unicorn (5.0.1) lib/unicorn/http_server.rb:562:in `process_client'
  unicorn (5.0.1) lib/unicorn/http_server.rb:658:in `worker_loop'
  unicorn (5.0.1) lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  unicorn (5.0.1) lib/unicorn/http_server.rb:132:in `start'
  unicorn (5.0.1) bin/unicorn:126:in `<top (required)>'


ucert@xxx:~$ rails -v
Rails 4.2.4
ucert@xxx:~$ gem list | grep twi
twitter-bootstrap-rails (3.2.0)
